config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create] do
    member do
      get :likes
    end
  end
  
  resources :homes, only: [:index]
  resources :posts, only: [:index, :create, :destroy]
  resources :notices, only: [:index, :new, :edit, :update, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: { maximum: 255 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :favorites,dependent: :destroy

  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :room, presence: true, length: { maximum: 4 },
                   format: { with: /\A[0-9]+\z/ },
                   uniqueness: { case_sensitive: false }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :posts
  has_many :favorites
  has_many :likes, through: :favorites, source: :post
  has_many :notices
  
  def feed_posts
    Post.where(id: self.like_ids).or(Post.where(user_id: self)) 
  end

  def feed_notices
    Notice
  end
  
  def like(post)
    self.favorites.find_or_create_by(post_id: post.id)
  end

  def unlike(post)
    favorite = self.favorites.find_by(post_id: post.id)
    favorite.destroy if favorite
  end

  def like?(post)
    self.likes.include?(post)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  include SessionsHelper
  include Pagy::Backend

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

def require_admin
    unless current_user.admin == true
      redirect_to root_path
    end
end


  def counts(user)
    @count_posts = user.posts.count
    @count_likes = user.favorites.count
    @count_notices = user.notices.count
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
   # before_action :require_user_logged_in
    
    def create
      post = Post.find(params[:post_id])
      current_user.like(post)
      flash[:success] = 'お気に入りに登録しました。'
      redirect_back(fallback_location: root_path)
    end

    def destroy
      post = Post.find(params[:post_id])
      current_user.unlike(post)
      flash[:success] = 'お気に入りを解除しました。'
      redirect_back(fallback_location: root_path)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :require_user_logged_in, only: [:index]

  def index
    @post = current_user.posts.build

    @pagy, @posts = pagy(current_user.feed_posts.order(id: :desc))
    @notices = Notice.all.order(id: :desc).limit(5)
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  before_action :require_admin, only: [:new, :edit, :destroy, :create, :update]

  def index
    @pagy, @notices = pagy(Notice.all.order(id: :desc))
  end

  def new
    @pagy, @notices = pagy(Notice.all.order(id: :desc))
    @notice = Notice.new
  end

  def create
    @notice = current_user.notices.build(notice_params)
    if @notice.save
      flash[:success] = 'お知らせを投稿しました。'
      redirect_to notices_path
    else
      @pagy, @notices = pagy(current_user.notices.order(id: :desc))
      flash[:danger] = 'お知らせの投稿に失敗しました。'
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @notices = Notice.where(id: params[:id])
#    @pagy, @notices = pagy(Notice.all.order(id: :desc))
    @notice = Notice.find(params[:id])
  end

  def update
    @notice = Notice.find(params[:id])

    if @notice.update(notice_params)
      flash[:success] = 'お知らせは正常に更新されました'
      redirect_back(fallback_location: root_path)
#      redirect_to notices_path
    else
      @pagy, @notices = pagy(current_user.notices.order(id: :desc))
      flash.now[:danger] = 'お知らせは更新されませんでした'
      render 'notices/index'
    end
  end

  def destroy
    @notice.destroy
    flash[:success] = 'お知らせを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private

  def notice_params
    params.require(:notice).permit(:content)
  end

  def correct_user
    @notice = current_user.notices.find_by(id: params[:id])
    unless @notice
      redirect_to root_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]

  def index
    @post = current_user.posts.build
    @pagy, @posts = pagy(Post.all.order(id: :desc))
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = 'メッセージを投稿しました。'
      redirect_to  homes_path
    else
      @pagy, @posts = pagy(current_user.posts.order(id: :desc))
      flash[:danger] = 'メッセージの投稿に失敗しました。'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @post.destroy
    flash[:success] = 'メッセージを削除しました。'
    redirect_back(fallback_location: root_path)
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    room = params[:session][:room]
    password = params[:session][:password]
    if login(room, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(room, password)
    @user = User.find_by(room: room)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      redirect_to  controller: :homes, action: :index
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :likes]
  def index
    @pagy, @users = pagy(User.order(id: :desc), items: 25)
  end

  def show
    @user = User.find(params[:id])
    @pagy, @posts = pagy(@user.posts.order(id: :desc))
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      session[:user_id] = @user.id
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end

  def likes
    @user = User.find(params[:id])
    @pagy, @likes = pagy(@user.likes)
    counts(@user)
  end

  private

  def user_params
    params.require(:user).permit(:room, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/favorites/_like_button.html.erb
<% if current_user.like?(post) %>
  <%= form_with(model: current_user.favorites.find_by(post_id: post.id), method: :delete) do |f| %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= f.submit 'UNLIKE', class: 'btn btn-secondary btn-sm' %>
  <% end %>
<% else %>
  <%= form_with(model: current_user.favorites.build) do |f| %>
    <%= hidden_field_tag :post_id, post.id %>
    <%= f.submit 'LIKE', class: 'btn btn-primary btn-sm' %>
  <% end %>
<% end %>

app/views/homes/index.html.erb
<div class="row">
<aside class="col-sm-4">
  <%= render 'layouts/menu' %>
</aside>
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        マイ投稿
      </div>
      <div class="card-body">
        <%= form_with(model: @post) do |f| %>
        <div class="mb-1">
          <%= f.text_area :content, class: 'form-control', rows: 3 %>
        </div>
        <div class="mb-3 border-bottom">
          <%= f.submit '投稿する', class: 'btn btn-primary btn-sm mb-1' %>
          <% end %>
        </div>
        <div>
          <%= render 'posts/posts_homes', posts: @posts %>
        </div>
      </div>
    </div>
  </div>    
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        管理室より（最新５件）
      </div>
      <div class="card-body">
        <%= render 'notices/notices_homes', notices: @notices %>
      </div>
    </div>
  </div>

</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_menu.html.erb
  <div class="card">
    <div class="card-header">
        ユーザメニュー
    </div>
  <div class="card-body">
    <div>
      <img class="rounded me-2 mb-1" src="<%= gravatar_url(current_user, { size: 32 }) %>" alt="">
      <%= current_user.room %><% if current_user.admin == true %>（管理室）<% end %>
    </div>
    <div class="mb-3"><%= link_to "マイホーム", homes_path, class: 'btn btn-outline-primary btn-sm w-100' %></div>
    <div class="mb-3"><%= link_to "管理室からのお知らせ", notices_path, class: 'btn btn-outline-primary btn-sm w-100' %></div>
    <div class="mb-3"><%= link_to "投稿一覧", posts_path, class: 'btn btn-outline-primary btn-sm w-100' %></div>
  </div>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">OURHOME</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
          <p class="navbar-text">
            <span class="badge bg-light text-dark mt-3">
             Room: <%= current_user.room %>
            <% if current_user.admin == true %>
              (admin)
            <% end %>
            </span>
          </p>

            <ul class="navbar-nav">
              <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
            </ul>

        <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to '新規登録', signup_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>OURHOME</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/notices/_notices.html.erb
<% if notices.any? %>
  <ul class="list-unstyled mt-2">
    <% notices.each do |notice| %>
      <li class="d-flex">
        <div>
          <div>
            <span class="text-muted"> <%= notice.created_at.to_s(:datetime_jp) %></span>
          </div>
          <div>
            <p><%= notice.content %></p>
          </div>
          <div>
            <% if current_user.admin == true %>
              <% if action_name != "edit" %>
                <%= link_to '編集する', edit_notice_path(notice) %>
              <% end %>
              <%= link_to "削除する", notice, method: :delete, data: { confirm: "本当に削除しますか？" } %>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/notices/_notices_homes.html.erb
<% if notices.any? %>
  <ul class="list-unstyled mt-2">
    <% notices.each do |notice| %>
      <li class="d-flex">
        <div>
          <div>
            <span class="text-muted"> <%= notice.created_at.to_s(:datetime_jp) %></span>
          </div>
          <div>
            <p><%= notice.content %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/notices/edit.html.erb
<div class="row">
  <aside class="col-sm-4">
    <%= render 'layouts/menu' %>
  </aside>
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        編集中のお知らせ
      </div>
      <div class="card-body">
        <%= render 'notices/notices', notices: @notices %>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <%= form_with(model: @notice) do |f| %>
      <div>
        <img class="rounded me-2 mb-1" src="<%= gravatar_url(current_user, { size: 32 }) %>" alt="">
        <%= current_user.room %>　お知らせの編集
      </div>
      <div class="mb-1">
        <%= f.text_area :content, class: 'form-control', rows: 9 %>
      </div>
      <div class="mb-3">
        <%= f.submit '反映する', class: 'btn btn-primary btn-sm mb-1' %>
      </div>
    <% end %>

  </div>

</div>

app/views/notices/index.html.erb
<div class="row">
  <aside class="col-sm-4">
    <%= render 'layouts/menu' %>
  </aside>
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        お知らせ一覧
      </div>
      <div class="card-body">
        <%= render 'notices/notices', notices: @notices %>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <% if current_user.admin == true %>
    <div class="card">
      <div class="card-header">
        管理者メニュー
      </div>
      <div class="card-body">
        <div class="mb-3">
          <%= link_to "新たなお知らせの追加", new_notice_path, class: 'btn btn-outline-danger btn-sm w-100' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/notices/new.html.erb
<div class="row">
  <aside class="col-sm-4">
    <%= render 'layouts/menu' %>
  </aside>
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        お知らせ一覧
      </div>
      <div class="card-body">
        <%= render 'notices/notices', notices: @notices %>
      </div>
    </div>
  </div>
  <div class="col-sm-4">
    <%= form_with(model: @notice) do |f| %>
      <div>
        <img class="rounded me-2 mb-1" src="<%= gravatar_url(current_user, { size: 32 }) %>" alt="">
        <%= current_user.room %><% if current_user.admin == true %>（管理室）<% end %>　新たなお知らせ
      </div>
      <div class="mb-1">
        <%= f.text_area :content, class: 'form-control', rows: 9 %>
      </div>
      <div class="mb-3">
        <%= f.submit '投稿する', class: 'btn btn-primary btn-sm mb-1' %>
      </div>
    <% end %>

  </div>

</div>

app/views/posts/_posts.html.erb
<% if posts.any? %>
  <ul class="list-unstyled mt-2">
    <% posts.each do |post| %>
      <li class="d-flex">
        <img class="rounded me-2 mb-5" src="<%= gravatar_url(post.user, { size: 64 }) %>" alt="">
        <div>
          <div>
            <%= post.user.room %><span class="text-muted"> <%= post.created_at.to_s(:datetime_jp) %></span>
          </div>
          <div>
            <p><%= post.content %></p>
          </div>
          <div>
            <div class="btn-group" role="group" aria-label="button-group">
              <%= render 'favorites/like_button', post: post %>
              <% if current_user == post.user or current_user.admin == true %>
                <%= link_to "削除", post, method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-danger btn-sm' %>
              <% end %>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/posts/_posts_homes.html.erb
<% if posts.any? %>
  <ul class="list-unstyled mt-2">
    <% posts.each do |post| %>
      <li class="d-flex">
        <img class="rounded me-2 mb-5" src="<%= gravatar_url(post.user, { size: 64 }) %>" alt="">
        <div>
          <div>
            <%= post.user.room %> <span class="text-muted"> <%= post.created_at.to_s(:datetime_jp) %></span>
          </div>
          <div>
            <p><%= post.content %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/posts/index.html.erb
<div class="row">
  <aside class="col-sm-4">
    <%= render 'layouts/menu' %>
  </aside>
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        投稿一覧
      </div>
      <div class="card-body">
        <%= render 'posts/posts', posts: @posts %>
      </div>
    </div>
  </div>    
  <div class="col-sm-4">
    <div class="card">
      <div class="card-header">
        新規投稿
      </div>
      <div class="card-body">
        <%= form_with(model: @post) do |f| %>
        <div>
          <img class="rounded me-2 mb-1" src="<%= gravatar_url(current_user, { size: 32 }) %>" alt="">
          <%= current_user.room %><% if current_user.admin == true %>（管理室）<% end %>
        </div>
        <div class="mb-1">
          <%= f.text_area :content, class: 'form-control', rows: 9 %>
        </div>
        <div class="mb-3 border-bottom">
          <%= f.submit '投稿する', class: 'btn btn-primary btn-sm mb-1' %>
        </div>
          <% end %>
      </div>
    </div>
  </div>

</div>

app/views/toppages/index.html.erb
<div class="bg-secondary p-3 p-sm-5 my-4 rounded">
  <div class="text-center text-white">
    <h1>Welcome to the OURHOME</h1>
  </div>
</div>

<div class="d-grid gap-2 col-3 mx-auto">
  <%= link_to 'アカウント作成', signup_path, class: 'btn btn-lg btn-primary' %>
  <%= link_to 'ログイン', login_path, class: 'btn btn-lg btn-outline-primary' %>
</div>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="mb-3 d-flex">
        <img class="rounded me-2" src="<%= gravatar_url(user, { size: 64 }) %>" alt="">
        <div>
          <div>
            <%= user.room %>
          </div>
          <div>
            <p><%= link_to 'Room profile', user_path(user), class: "text-decoration-none" %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>新規登録</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :room, '部屋番号' %>
        <%= f.number_field :room, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'パスワード（確認）' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit '登録', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.room %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>">Posts  <span class="badge bg-secondary"><%= @count_posts %></span></a></li>
      <li class="nav-item"><a href="#" class="nav-link">Followings</a></li>
      <li class="nav-item"><a href="#" class="nav-link">Followers</a></li>
    </ul>
    <%= render 'posts/posts', microposts: @posts %>
  </div>
</div>